### ISSUE TITLE
[1.8.9] Cannot join servers with ViaForge 3.6.1

### ISSUE THREAD

**Issue by HowardZHY** [Sk1erLLC/Patcher#177]
https://modrinth.com/mod/ViaForge

```
[14:46:47] [Netty Client IO #7/INFO] [FML/]: [Netty Client IO #7] Client side vanilla connection established
[14:46:48] [Netty Client IO #7/ERROR] [FML/]: Exception caught during firing event net.minecraftforge.fml.common.network.FMLNetworkEvent$ClientConnectedToServerEvent@4461514e:
java.nio.channels.ClosedChannelException
[14:46:48] [Netty Client IO #7/ERROR] [FML/]: Index: 2 Listeners:
[14:46:48] [Netty Client IO #7/ERROR] [FML/]: 0: NORMAL
[14:46:48] [Netty Client IO #7/ERROR] [FML/]: 1: ASM: club.sk1er.patcher.Patcher@15fcd8d8 connectToServer(Lnet/minecraftforge/fml/common/network/FMLNetworkEvent$ClientConnectedToServerEvent;)V
[14:46:48] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_312]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_312]
	at net.minecraft.util.Util.func_181617_a(Util.java:20) [g.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1014) [ave.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349) [ave.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
Caused by: java.lang.NullPointerException
	at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:249) ~[bcy.class:?]
	at com.mumfrey.liteloader.client.PacketEventsClient.handlePacket(PacketEventsClient.java:140) ~[PacketEventsClient.class:1.8.9-SNAPSHOT+unknown-b0.git-unknown]
	at com.mumfrey.liteloader.core.PacketEvents.handlePacketEvent(PacketEvents.java:214) ~[PacketEvents.class:1.8.9-SNAPSHOT+unknown-b0.git-unknown]
	at com.mumfrey.liteloader.core.PacketEvents.handlePacket(PacketEvents.java:156) ~[PacketEvents.class:1.8.9-SNAPSHOT+unknown-b0.git-unknown]
	at com.mumfrey.liteloader.core.PacketEvents.handlePacket(PacketEvents.java:143) ~[PacketEvents.class:1.8.9-SNAPSHOT+unknown-b0.git-unknown]
	at com.mumfrey.liteloader.core.event.EventProxy$2.$event00006(Unknown Source) ~[?:1.8.9-SNAPSHOT+unknown-b0.git-unknown]
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile) ~[gt.class:?]
	at net.minecraft.network.PacketThreadUtil$1.redirect$zfj000$Patcher_1_8_9_20_1_8_9_$patcher$ignorePacketsFromClosedConnections(PacketThreadUtil.java:523) ~[fh$1.class:?]
[14:46:49] [Netty Client IO #8/ERROR] [FML/]: HandshakeMessageHandler exception
java.lang.RuntimeException: java.nio.channels.ClosedChannelException
```

**Comment by HowardZHY** [comment]
Unrelated with the Mixin mentioned in stacktrace, maybe
https://github.com/Sk1erLLC/Patcher/blob/master/src/main/java/club/sk1er/patcher/asm/network/NetHandlerPlayClientTransformer.java

**Comment by HowardZHY** [comment]
It's not that ASM class, I've used Recaf to clear the transform method but still happens

**Comment by Sychic** [comment]
This issue stems from [patcher's server version checker](https://github.com/Sk1erLLC/Patcher/blob/master/src/main/java/club/sk1er/patcher/util/status/ProtocolVersionDetector.java#L29). ViaForge tries to capture each server's version via either the game pinging the server or from the connect screen. There are no other places for patcher to try and provide the version. 

I would say this is their issue as they should handle no version being stored for a server.
