### ISSUE TITLE
Crash at end of startup due to resource pack font renderer incompatibility.

### ISSUE THREAD

**Issue by Minimunch57** [Sk1erLLC/Patcher#38]
Hello,

I launched Minecraft just like normal today, and everything loaded up fine. I joined Hypixel and was about to start a game, but I decided to switch resource packs. I tabbed out while it loaded, but realized that my Minecraft had crashed. I initially thought it was because I tabbed out and something broke, but that was not the issue. After multiple attempts to relaunch the game, it continued to crash after the 7/7 loading progress during Forge startup. Basically, it would crash as soon as it attempted to render the main screen.

After reading through the crash log, it seems like there's an issue with the optimized font renderer and the font used by the John Smith Legacy resource pack that I attempted to load. To be sure that it was Patcher, I removed the mod, launched Forge normally with no issues, switched packs, then put Patcher back into my mods folder and relaunched successfully. I am providing all of the potentially relevant information below for debugging. Let me know if anything else is needed, or if I am just wrong and there is another issue.

### Information

**Version:** 1.8.9 (Forge - Version: 1.8.9.11.15.1.2318)
**Other Mods (_Should_ Be Irrelevant):**
![image](https://user-images.githubusercontent.com/43156167/142982512-7195b5b8-62ef-47af-ab90-7927ae2bd514.png)
**Resource Pack:** John Smith Legacy 1.8.9 v1.3.3
[John Smith Legacy 1.8.9 v1.3.33.zip](https://github.com/Sk1erLLC/Patcher/files/7586254/John.Smith.Legacy.1.8.9.v1.3.33.zip)
(Looking at it now, the pack seems to handle some things in a bit of an odd way. Not sure if this would make the pack completely incompatible given the way that Patcher handles the fonts, but I don't know.)

**Additional details:**
- Running Windows 10, NVIDIA graphics card on next-to-latest drivers.
- Launching with fullscreen mode enabled or disabled did not change anything; the crash log below was taken while it was disabled.
- Sk1er mods are fully up-to-date, as well as the Minecraft launcher and Forge.
- The issue only presented itself when this specific resource pack had been selected, as specified in the summary above.

### Simplified Crash Log:
```
WARNING: coremods are present:
  OptifinePatcherTweaker (Sk1er_Old_Animations-1.0_-_beta_7.jar)
  ModTweaker (Patcher-1.7.0 (1.8.9).jar)
  FMLLoadingPlugin (Skypixel-0.0.6.jar)
  FMLLoadingPlugin (Sk1er_Old_Animations-1.0_-_beta_7.jar)
  PatcherTweaker (Patcher-1.7.0 (1.8.9).jar)

Time: 11/23/21 1:26 AM
Description: Rendering screen

java.lang.IllegalArgumentException: Dimensions (width=65536 height=69632) are too large
	at java.awt.image.SampleModel.<init>(SampleModel.java:130)
	at java.awt.image.SinglePixelPackedSampleModel.<init>(SinglePixelPackedSampleModel.java:144)
	at java.awt.image.Raster.createPackedRaster(Raster.java:773)
	at java.awt.image.Raster.createPackedRaster(Raster.java:475)
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1032)
	at java.awt.image.BufferedImage.<init>(BufferedImage.java:340)
	at club.sk1er.patcher.hooks.FontRendererHook.create(FontRendererHook.java:83)
	at club.sk1er.patcher.hooks.FontRendererHook.renderStringAtPos(FontRendererHook.java:132)
	at net.minecraft.client.gui.FontRenderer.handler$patcher$useOptimizedRendering$zjm000(FontRenderer.java:2745)
	at net.minecraft.client.gui.FontRenderer.func_78255_a(FontRenderer.java)
	at net.minecraft.client.gui.FontRenderer.func_180455_b(FontRenderer.java:702)
	at net.minecraft.client.gui.FontRenderer.func_175065_a(FontRenderer.java:427)
	at net.minecraft.client.gui.FontRenderer.func_175063_a(FontRenderer.java:394)
	at net.minecraft.client.gui.Gui.func_73732_a(SourceFile:99)
	at net.minecraft.client.gui.GuiMainMenu.func_73863_a(GuiMainMenu.java:632)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:311)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1436)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.GuiMainMenu
	Mouse location: Scaled: (0, 239). Absolute: (0, 0)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2
Stacktrace:
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1436)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

Appreciate the hard work and again let me know if I can be of any more help with this issue. Thank you.

**Comment by 08msawyer** [comment]
We've had this reported once before. Basically it boils down to patcher trying to make a single image with all the characters of your font, for performance purposes, but your font is so high-resolution that the combined image is too big for Java to handle. Probably good to have an issue tracking this. In the meantime you should be able to disable the optimized font renderer in the config file, use another pack, or remove the font textures from your current pack.

**Comment by LlamaLad7** [comment]
We've had this reported once before. Basically it boils down to patcher trying to make a single image with all the characters of your font, for performance purposes, but your font is so high-resolution that the combined image is too big for Java to handle. Probably good to have an issue tracking this. In the meantime you should be able to disable the optimized font renderer in the config file, use another pack, or remove the font textures from your current pack.

**Comment by Apple26j** [comment]
> We've had this reported once before with the same pack. I believe it boils down to Patcher trying to make a single image with all the characters of your font, for performance purposes, but your font is so high-resolution that the combined image is too big for Java to handle. Probably good to have an issue tracking this. In the meantime you should be able to disable the optimized font renderer in the config file, use another pack, or remove the font textures from your current pack.

Java CAN handle it.

**Comment by PiauTW** [comment]
I got the same problem bro
but I really want to keep my fonts
how can I solve this issue?
