### ISSUE TITLE
Taking a screenshot sometimes gives you a NPE 

### ISSUE THREAD

**Issue by SystemlessDev** [Sk1erLLC/Patcher#73]
No real way to reproduce the issue outside of taking a bunch of screenshots until it happens. 

```
[19:02:19] [Essential 13/ERROR]: Failed to capture screenshot.
java.lang.NullPointerException
    at net.minecraft.client.gui.GuiNewChat.func_146242_c(SourceFile:254) ~[avt.class:?]
    at net.minecraft.client.gui.GuiNewChat.func_146237_a(SourceFile:135) ~[avt.class:?]
    at net.minecraft.client.gui.GuiNewChat.func_146234_a(SourceFile:129) ~[avt.class:?]
    at club.sk1er.patcher.util.screenshot.AsyncScreenshots.sendChatMessages(AsyncScreenshots.java:161) ~[AsyncScreenshots.class:?]
    at club.sk1er.patcher.util.screenshot.AsyncScreenshots.run(AsyncScreenshots.java:82) [AsyncScreenshots.class:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_333]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_333]
    at java.lang.Thread.run(Thread.java:750) [?:1.8.0_333]
    ```

**Comment by cbyrneee** [comment]
Was able to reproduce this by spamming the F2 key while joining a world, looking into a fix now.
